### ISSUE TITLE
Issue with ns3.34

### ISSUE THREAD

**Issue by AlLoi2** [djvergad/dash#23]
When executing the example dash-example.cc with ns version 3.34 the execution works fine (output is as expected), however after this execution I can no longer use the waf commands to execute any simulations in ns3 due to this error:

_Traceback (most recent call last):
  File "/home/alejandro/Desktop/bake/source/ns-3.34/.waf3-2.0.21-c6c9a875365426e5928462b9b74d40b5/waflib/Scripting.py", line 119, in waf_entry_point
    run_commands()
  File "/home/alejandro/Desktop/bake/source/ns-3.34/.waf3-2.0.21-c6c9a875365426e5928462b9b74d40b5/waflib/Scripting.py", line 182, in run_commands
    ctx=run_command(cmd_name)
  File "/home/alejandro/Desktop/bake/source/ns-3.34/.waf3-2.0.21-c6c9a875365426e5928462b9b74d40b5/waflib/Scripting.py", line 173, in run_command
    ctx.execute()
  File "/home/alejandro/Desktop/bake/source/ns-3.34/.waf3-2.0.21-c6c9a875365426e5928462b9b74d40b5/waflib/Scripting.py", line 375, in execute
    return execute_method(self)
  File "/home/alejandro/Desktop/bake/source/ns-3.34/.waf3-2.0.21-c6c9a875365426e5928462b9b74d40b5/waflib/Build.py", line 93, in execute
    self.execute_build()
  File "/home/alejandro/Desktop/bake/source/ns-3.34/.waf3-2.0.21-c6c9a875365426e5928462b9b74d40b5/waflib/Build.py", line 100, in execute_build
    self.compile()
  File "/home/alejandro/Desktop/bake/source/ns-3.34/.waf3-2.0.21-c6c9a875365426e5928462b9b74d40b5/waflib/Build.py", line 167, in compile
    self.producer.start()
  File "/home/alejandro/Desktop/bake/source/ns-3.34/.waf3-2.0.21-c6c9a875365426e5928462b9b74d40b5/waflib/Runner.py", line 275, in start
    self.refill_task_list()
  File "/home/alejandro/Desktop/bake/source/ns-3.34/.waf3-2.0.21-c6c9a875365426e5928462b9b74d40b5/waflib/Runner.py", line 152, in refill_task_list
    tasks=next(self.biter)
  File "/home/alejandro/Desktop/bake/source/ns-3.34/.waf3-2.0.21-c6c9a875365426e5928462b9b74d40b5/waflib/Build.py", line 416, in get_build_iterator
    self.post_group()
  File "/home/alejandro/Desktop/bake/source/ns-3.34/.waf3-2.0.21-c6c9a875365426e5928462b9b74d40b5/waflib/Build.py", line 399, in post_group
    tgpost(tg)
  File "/home/alejandro/Desktop/bake/source/ns-3.34/.waf3-2.0.21-c6c9a875365426e5928462b9b74d40b5/waflib/Build.py", line 359, in tgpost
    f()
  File "/home/alejandro/Desktop/bake/source/ns-3.34/.waf3-2.0.21-c6c9a875365426e5928462b9b74d40b5/waflib/TaskGen.py", line 123, in post
    v()
  File "/home/alejandro/Desktop/bake/source/ns-3.34/src/wscript", line 717, in apply_ns3moduleheader
    for source in sorted(ns3headers.headers):
AttributeError: 'task_gen' object has no attribute 'headers'_

Is this caused because there is no ns-3.34 compatibility ?

**Comment by AlLoi2** [comment]
This was a mistake in my part, code runs perfectly fine
